title: Hamza Salah
logo: "/assets/hs.jpg" 

description: >
  I’m a Data Scientist with 4+ years of combined experience in retail, logistics, and analytics,
  with additional strengths in strategy and sales. Currently pursuing a Master’s in Data Science at Bellevue University.
  I’ve built projects using SQL, Python, and Tableau to solve real-world problems in healthcare, education, and operations.
  <br><br>
  [LinkedIn](https://www.linkedin.com/in/hamzamsalah/)[Github](https://github.com/hamzamsalah)

theme: jekyll-theme-minimal

colors:
  crimson: '#900C3F'
