title: Hamza Salah
logo: "/assets/hs.jpg" 

description: >
  *Data Science M.S. candidate passionate about analyzing data, building predictive models, and applying machine learning to real-world problems.*

  <br><br>
  <!-- Clickable Icons -->
  <a href="https://www.linkedin.com/in/hamzamsalah/" target="_blank">
    <img src="/assets/logos/linkedin.svg" alt="Linkedin" width="30" height="30" style="vertical-align:middle;">
  </a>
  <a href="https://github.com/hamzamsalah" target="_blank">
    <img src="/assets/logos/github.svg" alt="GitHub" width="30" height="30" style="vertical-align:middle;">
  </a>
  <a href="https://public.tableau.com/app/profile/hamzamsalah/vizzes" target="_blank">
    <img src="/assets/logos/tableau.svg"  alt="Tableau" width="30" height="30" style="vertical-align:middle;">
  </a>
  <a href="https://medium.com/@hamzamsalah" target="_blank">
    <img src="/assets/logos/medium.svg" alt="Medium" width="30" height="30" style="vertical-align:middle;">
  </a>


theme: jekyll-theme-minimal

colors:
  crimson: '#900C3F'
